const areaActionTypes = {
  SET_CURRENT_AREA: "SET_CURRENT_AREA",
  SET_CURRENT_AREA_NULL: "SET_CURRENT_AREA_NULL",
  SET_CURRENT_AREAS: "SET_CURRENT_AREAS",
  SET_CURRENT_AREAS_NULL: "SET_CURRENT_AREAS_NULL",
};

export default areaActionTypes;
